name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:
      ubuntu-latest
      # - name: Checkout Main Branch
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #     ref: main

      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "16.x"

      # - name: Install Dependencies
      #   run: npm install

      # - name: Setting up Environment Variables
      #   env:
      #     NEXT_PUBLIC_MYSQL_DATABASE_HOST: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_HOST }}
      #     NEXT_PUBLIC_MYSQL_DATABASE_PORT: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PORT }}
      #     NEXT_PUBLIC_MYSQL_DATABASE_USER: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_USER }}
      #     NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD }}
      #     NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      #   run: echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> $GITHUB_ENV

      # - name: Build Application
      #   run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: unnecessary

      # - name: Adding Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     touch ~/.ssh/authorized_keys
      #     ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run: rsync -avz . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIRECTORY }}
    steps:
      - name: Run code on VPS
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Connect to the directory where your code is located
            cd /var/www/guest_process

            # Install dependencies, build, or any other necessary steps
            npm ci
            npm run build

            # Install PM2 globally
            npm install -g pm2

            # Use PM2 to start your application
            pm2 start your_app.js
