name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Setting up Environment Variables
        env:
          NEXT_PUBLIC_MYSQL_DATABASE_HOST: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_HOST }}
          NEXT_PUBLIC_MYSQL_DATABASE_PORT: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PORT }}
          NEXT_PUBLIC_MYSQL_DATABASE_USER: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_USER }}
          NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> $GITHUB_ENV

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: unnecessary

      # - name: Adding Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     touch ~/.ssh/authorized_keys
      #     ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run: rsync -avz . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIRECTORY }}

      # - name: Restarting PM2
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
      #     pm2 restart guest_process

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/guest_process
            npm install
            npm run build
            pm2 restart guest_process
