name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # - name: Install Dependencies
      #   run: npm install

      - name: Setting up Environment Variables
        env:
          NEXT_PUBLIC_MYSQL_DATABASE_HOST: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_HOST }}
          NEXT_PUBLIC_MYSQL_DATABASE_PORT: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PORT }}
          NEXT_PUBLIC_MYSQL_DATABASE_USER: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_USER }}
          NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD: ${{ secrets.NEXT_PUBLIC_MYSQL_DATABASE_PASSWORD }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> $GITHUB_ENV

      # - name: Build Application
      #   run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: unnecessary

      # - name: Adding Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     touch ~/.ssh/authorized_keys
      #     ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/guest_process
            npm i
            npm run build
            pm2 restart guest_process
